const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '../.env');
let apiKey = process.env.API_KEY_IA || '';

if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  const match = envContent.match(/^API_KEY_IA\s*=\s*(.*)$/m);
  if (match && match[1]) {
    apiKey = match[1].trim();
  }
}

// Strip surrounding quotes if present
if (apiKey.startsWith('"') && apiKey.endsWith('"')) {
  apiKey = apiKey.substring(1, apiKey.length - 1);
} else if (apiKey.startsWith("'") && apiKey.endsWith("'")) {
  apiKey = apiKey.substring(1, apiKey.length - 1);
}

const outputPath = path.join(__dirname, '../src/app/core/env.ts');
const outputContent = `// Autogenerated file. Do not commit.
export const env = {
  API_KEY_IA: ${JSON.stringify(apiKey)}
};
`;

fs.writeFileSync(outputPath, outputContent, 'utf8');
console.log('Environment file generated successfully at', outputPath);
